from typing import Dict, List, Optional, Protocol
from uuid import UUID

from src.domain.entities.school import School
from src.domain.entities.student import Student
from src.domain.entities.invoice import Invoice, Payment
from src.domain.enums import InvoiceStatus


class SchoolRepository(Protocol):
    async def get_by_id(self, school_id: UUID) -> Optional[School]: ...
    async def get_all(self, skip: int = 0, limit: int = 100, filters: Optional[Dict] = None) -> List[School]: ...
    async def save(self, school: School) -> School: ...
    async def count(self, filters: Optional[Dict] = None) -> int: ...
    async def get_student_count(self, school_id: UUID, active_only: bool = True) -> int: ...
    async def get_school_financials(self, school_id: UUID) -> dict: ...


class StudentRepository(Protocol):
    async def get_by_id(self, student_id: UUID) -> Optional[Student]: ...
    async def get_all(self, skip: int = 0, limit: int = 100, filters: Optional[Dict] = None) -> List[Student]: ...
    async def get_by_school(self, school_id: UUID, skip: int = 0, limit: int = 100, active_only: bool = False) -> List[Student]: ...
    async def save(self, student: Student) -> Student: ...
    async def count(self, filters: Optional[Dict] = None) -> int: ...


class InvoiceRepository(Protocol):
    async def get_by_id(self, invoice_id: UUID) -> Optional[Invoice]: ...
    async def get_with_payments(self, invoice_id: UUID) -> Optional[Invoice]: ...
    async def get_all(self, skip: int = 0, limit: int = 100, filters: Optional[Dict] = None) -> List[Invoice]: ...
    async def get_by_student(self, student_id: UUID, skip: int = 0, limit: int = 100, status: Optional[InvoiceStatus] = None) -> List[Invoice]: ...
    async def get_by_school(self, school_id: UUID, skip: int = 0, limit: int = 100, status: Optional[InvoiceStatus] = None) -> List[Invoice]: ...
    async def save(self, invoice: Invoice) -> Invoice: ...
    async def count(self, filters: Optional[Dict] = None) -> int: ...
    async def get_by_school_with_details(self, school_id: UUID, limit: int = 1000) -> list[dict]: ...
    async def get_overdue_invoices(self) -> List[Invoice]: ...
    async def update_overdue_status(self) -> int: ...
    async def get_overdue_by_school(self, school_id: UUID, limit: int = 50) -> list[dict]: ...


class PaymentRepository(Protocol):
    async def get_by_id(self, payment_id: UUID) -> Optional[Payment]: ...
    async def get_all(self, skip: int = 0, limit: int = 100, filters: Optional[Dict] = None) -> List[Payment]: ...
    async def get_by_invoice(self, invoice_id: UUID, skip: int = 0, limit: int = 100) -> List[Payment]: ...
    async def count(self, filters: Optional[Dict] = None) -> int: ...
