"""add_grades_and_billing_items

Revision ID: 1c309ae71d2f
Revises: 003
Create Date: 2026-02-27 21:00:52.713980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c309ae71d2f'
down_revision: Union[str, None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_items',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the billing item'),
    sa.Column('school_id', sa.UUID(), nullable=False, comment='Reference to the school this item belongs to'),
    sa.Column('name', sa.String(length=200), nullable=False, comment="Item name (e.g., 'Enrollment 2024', 'Lunch Service')"),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed description of the billing item'),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='Default amount for this item'),
    sa.Column('is_recurring', sa.Boolean(), nullable=False, comment='Whether this is a recurring monthly charge'),
    sa.Column('academic_year', sa.String(length=20), nullable=True, comment="Academic year (e.g., '2024', '2024-2025')"),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_billing_items_is_active', 'billing_items', ['is_active'], unique=False)
    op.create_index('ix_billing_items_school_id', 'billing_items', ['school_id'], unique=False)
    op.create_table('grades',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the grade'),
    sa.Column('school_id', sa.UUID(), nullable=False, comment='Reference to the school this grade belongs to'),
    sa.Column('name', sa.String(length=100), nullable=False, comment="Grade name (e.g., '5th Grade', '1ero Secundaria')"),
    sa.Column('monthly_fee', sa.Numeric(precision=12, scale=2), nullable=False, comment='Monthly tuition fee for this grade'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_grades_is_active', 'grades', ['is_active'], unique=False)
    op.create_index('ix_grades_school_id', 'grades', ['school_id'], unique=False)
    # NOTE: Removed drop_table('users') - User model is in separate file
    op.add_column('invoices', sa.Column('billing_item_id', sa.UUID(), nullable=True, comment='Reference to the billing item (for FEE/ENROLLMENT types)'))
    # Add invoice_type as nullable first, set default for existing rows, then make NOT NULL
    op.add_column('invoices', sa.Column('invoice_type', sa.String(length=20), nullable=True, comment='Invoice type: TUITION, ENROLLMENT, FEE, CUSTOM'))
    op.execute("UPDATE invoices SET invoice_type = 'CUSTOM' WHERE invoice_type IS NULL")
    op.alter_column('invoices', 'invoice_type', nullable=False)
    op.alter_column('invoices', 'id',
               existing_type=sa.UUID(),
               comment='Unique identifier for the invoice',
               existing_nullable=False)
    op.alter_column('invoices', 'student_id',
               existing_type=sa.UUID(),
               comment='Reference to the student being billed',
               existing_nullable=False)
    op.alter_column('invoices', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='Total invoice amount (max: 9,999,999,999.99)',
               existing_nullable=False)
    op.alter_column('invoices', 'due_date',
               existing_type=sa.DATE(),
               comment='Payment due date',
               existing_nullable=False)
    op.alter_column('invoices', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='Invoice status: PENDING, PARTIAL, PAID, OVERDUE, CANCELLED',
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::character varying"))
    op.alter_column('invoices', 'description',
               existing_type=sa.TEXT(),
               comment="Description of the charge (e.g., 'March 2024 Tuition')",
               existing_nullable=True)
    op.alter_column('invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the invoice was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('invoices', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the invoice was last updated',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_invoices_due_date', 'invoices', ['due_date'], unique=False)
    op.create_index('ix_invoices_invoice_type', 'invoices', ['invoice_type'], unique=False)
    op.create_index('ix_invoices_student_status', 'invoices', ['student_id', 'status'], unique=False)
    op.drop_constraint(op.f('invoices_student_id_fkey'), 'invoices', type_='foreignkey')
    op.create_foreign_key(None, 'invoices', 'billing_items', ['billing_item_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'invoices', 'students', ['student_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('payments', 'id',
               existing_type=sa.UUID(),
               comment='Unique identifier for the payment',
               existing_nullable=False)
    op.alter_column('payments', 'invoice_id',
               existing_type=sa.UUID(),
               comment='Reference to the invoice being paid',
               existing_nullable=False)
    op.alter_column('payments', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='Payment amount (must be positive)',
               existing_nullable=False)
    op.alter_column('payments', 'payment_date',
               existing_type=sa.DATE(),
               comment='Date when payment was received',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.alter_column('payments', 'method',
               existing_type=sa.VARCHAR(length=20),
               comment='Payment method: CASH, BANK_TRANSFER, CREDIT_CARD, DEBIT_CARD, OTHER',
               existing_nullable=False,
               existing_server_default=sa.text("'CASH'::character varying"))
    op.alter_column('payments', 'reference',
               existing_type=sa.VARCHAR(length=255),
               comment='External reference (check number, transaction ID, etc.)',
               existing_nullable=True)
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the payment was recorded',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_payments_method', 'payments', ['method'], unique=False)
    op.create_index('ix_payments_payment_date', 'payments', ['payment_date'], unique=False)
    op.drop_constraint(op.f('payments_invoice_id_fkey'), 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'invoices', ['invoice_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('schools', 'id',
               existing_type=sa.UUID(),
               comment='Unique identifier for the school',
               existing_nullable=False)
    op.alter_column('schools', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='Name of the educational institution',
               existing_nullable=False)
    op.alter_column('schools', 'address',
               existing_type=sa.VARCHAR(length=500),
               comment='Physical address of the school',
               existing_nullable=True)
    op.alter_column('schools', 'phone',
               existing_type=sa.VARCHAR(length=50),
               comment='Contact phone number',
               existing_nullable=True)
    op.alter_column('schools', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='Contact email address',
               existing_nullable=True)
    op.alter_column('schools', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Soft delete flag: False means logically deleted',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('schools', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the record was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('schools', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the record was last updated',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_schools_is_active', 'schools', ['is_active'], unique=False)
    op.create_index('ix_schools_name', 'schools', ['name'], unique=False)
    op.add_column('students', sa.Column('grade_id', sa.UUID(), nullable=True, comment="Reference to the student's grade/level"))
    op.alter_column('students', 'id',
               existing_type=sa.UUID(),
               comment='Unique identifier for the student',
               existing_nullable=False)
    op.alter_column('students', 'school_id',
               existing_type=sa.UUID(),
               comment='Reference to the school where student is enrolled',
               existing_nullable=False)
    op.alter_column('students', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               comment="Student's first name",
               existing_nullable=False)
    op.alter_column('students', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               comment="Student's last name",
               existing_nullable=False)
    op.alter_column('students', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='Student or parent/guardian email',
               existing_nullable=True)
    op.alter_column('students', 'grade',
               existing_type=sa.VARCHAR(length=50),
               comment='[DEPRECATED] Use grade_id instead. Legacy grade text field.',
               existing_nullable=True)
    op.alter_column('students', 'enrolled_at',
               existing_type=sa.DATE(),
               comment='Date when the student was enrolled',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.alter_column('students', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Soft delete flag: False means student has withdrawn',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('students', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the record was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('students', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the record was last updated',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_students_grade_id', 'students', ['grade_id'], unique=False)
    op.create_index('ix_students_is_active', 'students', ['is_active'], unique=False)
    op.create_index('ix_students_school_active', 'students', ['school_id', 'is_active'], unique=False)
    op.drop_constraint(op.f('students_school_id_fkey'), 'students', type_='foreignkey')
    op.create_foreign_key(None, 'students', 'grades', ['grade_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'students', 'schools', ['school_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_foreign_key(op.f('students_school_id_fkey'), 'students', 'schools', ['school_id'], ['id'])
    op.drop_index('ix_students_school_active', table_name='students')
    op.drop_index('ix_students_is_active', table_name='students')
    op.drop_index('ix_students_grade_id', table_name='students')
    op.alter_column('students', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the record was last updated',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('students', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the record was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('students', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Soft delete flag: False means student has withdrawn',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('students', 'enrolled_at',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Date when the student was enrolled',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.alter_column('students', 'grade',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='[DEPRECATED] Use grade_id instead. Legacy grade text field.',
               existing_nullable=True)
    op.alter_column('students', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Student or parent/guardian email',
               existing_nullable=True)
    op.alter_column('students', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="Student's last name",
               existing_nullable=False)
    op.alter_column('students', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="Student's first name",
               existing_nullable=False)
    op.alter_column('students', 'school_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Reference to the school where student is enrolled',
               existing_nullable=False)
    op.alter_column('students', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique identifier for the student',
               existing_nullable=False)
    op.drop_column('students', 'grade_id')
    op.drop_index('ix_schools_name', table_name='schools')
    op.drop_index('ix_schools_is_active', table_name='schools')
    op.alter_column('schools', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the record was last updated',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('schools', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the record was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('schools', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Soft delete flag: False means logically deleted',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('schools', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Contact email address',
               existing_nullable=True)
    op.alter_column('schools', 'phone',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Contact phone number',
               existing_nullable=True)
    op.alter_column('schools', 'address',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Physical address of the school',
               existing_nullable=True)
    op.alter_column('schools', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Name of the educational institution',
               existing_nullable=False)
    op.alter_column('schools', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique identifier for the school',
               existing_nullable=False)
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(op.f('payments_invoice_id_fkey'), 'payments', 'invoices', ['invoice_id'], ['id'])
    op.drop_index('ix_payments_payment_date', table_name='payments')
    op.drop_index('ix_payments_method', table_name='payments')
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the payment was recorded',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('payments', 'reference',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='External reference (check number, transaction ID, etc.)',
               existing_nullable=True)
    op.alter_column('payments', 'method',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Payment method: CASH, BANK_TRANSFER, CREDIT_CARD, DEBIT_CARD, OTHER',
               existing_nullable=False,
               existing_server_default=sa.text("'CASH'::character varying"))
    op.alter_column('payments', 'payment_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Date when payment was received',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.alter_column('payments', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='Payment amount (must be positive)',
               existing_nullable=False)
    op.alter_column('payments', 'invoice_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Reference to the invoice being paid',
               existing_nullable=False)
    op.alter_column('payments', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique identifier for the payment',
               existing_nullable=False)
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.create_foreign_key(op.f('invoices_student_id_fkey'), 'invoices', 'students', ['student_id'], ['id'])
    op.drop_index('ix_invoices_student_status', table_name='invoices')
    op.drop_index('ix_invoices_invoice_type', table_name='invoices')
    op.drop_index('ix_invoices_due_date', table_name='invoices')
    op.alter_column('invoices', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the invoice was last updated',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the invoice was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('invoices', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment="Description of the charge (e.g., 'March 2024 Tuition')",
               existing_nullable=True)
    op.alter_column('invoices', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Invoice status: PENDING, PARTIAL, PAID, OVERDUE, CANCELLED',
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::character varying"))
    op.alter_column('invoices', 'due_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Payment due date',
               existing_nullable=False)
    op.alter_column('invoices', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='Total invoice amount (max: 9,999,999,999.99)',
               existing_nullable=False)
    op.alter_column('invoices', 'student_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Reference to the student being billed',
               existing_nullable=False)
    op.alter_column('invoices', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique identifier for the invoice',
               existing_nullable=False)
    op.drop_column('invoices', 'invoice_type')
    op.drop_column('invoices', 'billing_item_id')
    # NOTE: Removed create_table('users') - User model is in separate file
    op.drop_index('ix_grades_school_id', table_name='grades')
    op.drop_index('ix_grades_is_active', table_name='grades')
    op.drop_table('grades')
    op.drop_index('ix_billing_items_school_id', table_name='billing_items')
    op.drop_index('ix_billing_items_is_active', table_name='billing_items')
    op.drop_table('billing_items')
    # ### end Alembic commands ###
